import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd,        
           cwd + '/include/',
           cwd + '/platform/inc/',
           os.path.abspath(os.path.join(cwd, '..', 'data_frame'))]

src += Glob('platform/src/*.c')
src += Glob('app/*.c')

objs = DefineGroup('rpmsg-port', src, depend = ['PKG_USING_RPMSG_LITE'], CPPPATH = CPPPATH)

Return('objs')
